David
Courseplay/courseplay pull request #6468
Opened 2020-12-10 20:16 UTC by schwiti6190

2020-12-10 21:40 UTC, pvaiko requested changes

2020-12-10 21:40 UTC, pvaiko commented on BunkersiloManager.lua
> +		sx, _, sz = localToWorld(Silo.bunkerSiloArea.start,-0.5,0,0) --start BunkerNode
a comment would be nice explaining what the purpose of these adjustments are...

2020-12-10 21:40 UTC, pvaiko commented on LevelCompactAIDriver.lua
> +	self.workWidth = 3
isn't this overwriting what the line above just calculated?

2020-12-10 21:40 UTC, pvaiko commented on CpManager.lua
> +	local text =string.format("%s\n %s",courseplay:loc('COURSEPLAY_YES_NO_FIELDSCAN'),courseplay:loc('COURSEPLAY_YES_NO_FIELDSCAN_DISCLAIMER'))
Could we rename COURSEPLAY_YES_NO_FIELDSCAN_DISCLAIMER to COURSEPLAY_SUPPORT_INFO or something, the text has nothing to do with field scanning (we just put it into the same dialog) and isn't really a disclaimer either :)

2020-12-11 12:14 UTC, merged

2020-12-11 14:22 UTC, Redrooster1-web commented
I Apprieciate all what you are doing, all of you. But how do i setup a c/p course to lvl  chaff/grass??????????

E-mail me at ajboyle873@gmail.com