diff changes
Courseplay/courseplay pull request #6751
Opened 2021-01-29 08:35 UTC by schwiti6190

- improves loading/unloading with multiple fillunits in mode 1/4/8
- slightly improves cover handling
- improves triggerspeed near stationary triggers

2021-01-29 08:50 UTC, schwiti6190 commented on AIDriver.lua
> +
Course:hasTriggerRaycast(startIx,driverClass,driverCallback)  callback,
sadly it's not working as intended, as raycast only seem to detect node objects, but not a trigger bounding box of for example a fueltrigger of a fuel refill trailer.
=> so it's not used right now

2021-01-29 08:52 UTC, schwiti6190 commented on FieldSupplyAIDriver.lua
Changes the inheritance to GrainTransportAIDriver, as we don't need the field course and so on. 
Might have to heck if this change impactes autodrive setup.

2021-01-29 08:57 UTC, schwiti6190 commented on AIDriver.lua
for now we are still using the old self.triggerHandler:isInTrigger(), which uses the old triggers.lua code, might be a good idea to not depent on that code in the long run

2021-02-01 13:10 UTC, pvaiko requested changes
Looks like I forgot to submit this on Friday...

2021-02-02 13:37 UTC, schwiti6190 commented
@pvaiko thx for your feedback, I will have a look and try to adjust your ideas :)

2021-02-02 13:37 UTC, closed without merging